// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gin-api-demo/ent/album"
	"github.com/gin-api-demo/ent/predicate"
)

// AlbumUpdate is the builder for updating Album entities.
type AlbumUpdate struct {
	config
	hooks    []Hook
	mutation *AlbumMutation
}

// Where appends a list predicates to the AlbumUpdate builder.
func (au *AlbumUpdate) Where(ps ...predicate.Album) *AlbumUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetUpdateTime sets the "update_time" field.
func (au *AlbumUpdate) SetUpdateTime(t time.Time) *AlbumUpdate {
	au.mutation.SetUpdateTime(t)
	return au
}

// SetTitle sets the "title" field.
func (au *AlbumUpdate) SetTitle(s string) *AlbumUpdate {
	au.mutation.SetTitle(s)
	return au
}

// SetArtist sets the "artist" field.
func (au *AlbumUpdate) SetArtist(s string) *AlbumUpdate {
	au.mutation.SetArtist(s)
	return au
}

// SetPrice sets the "price" field.
func (au *AlbumUpdate) SetPrice(i int) *AlbumUpdate {
	au.mutation.ResetPrice()
	au.mutation.SetPrice(i)
	return au
}

// AddPrice adds i to the "price" field.
func (au *AlbumUpdate) AddPrice(i int) *AlbumUpdate {
	au.mutation.AddPrice(i)
	return au
}

// Mutation returns the AlbumMutation object of the builder.
func (au *AlbumUpdate) Mutation() *AlbumMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AlbumUpdate) Save(ctx context.Context) (int, error) {
	au.defaults()
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AlbumUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AlbumUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AlbumUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (au *AlbumUpdate) defaults() {
	if _, ok := au.mutation.UpdateTime(); !ok {
		v := album.UpdateDefaultUpdateTime()
		au.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AlbumUpdate) check() error {
	if v, ok := au.mutation.Price(); ok {
		if err := album.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "Album.price": %w`, err)}
		}
	}
	return nil
}

func (au *AlbumUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(album.Table, album.Columns, sqlgraph.NewFieldSpec(album.FieldID, field.TypeInt))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.UpdateTime(); ok {
		_spec.SetField(album.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := au.mutation.Title(); ok {
		_spec.SetField(album.FieldTitle, field.TypeString, value)
	}
	if value, ok := au.mutation.Artist(); ok {
		_spec.SetField(album.FieldArtist, field.TypeString, value)
	}
	if value, ok := au.mutation.Price(); ok {
		_spec.SetField(album.FieldPrice, field.TypeInt, value)
	}
	if value, ok := au.mutation.AddedPrice(); ok {
		_spec.AddField(album.FieldPrice, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{album.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AlbumUpdateOne is the builder for updating a single Album entity.
type AlbumUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AlbumMutation
}

// SetUpdateTime sets the "update_time" field.
func (auo *AlbumUpdateOne) SetUpdateTime(t time.Time) *AlbumUpdateOne {
	auo.mutation.SetUpdateTime(t)
	return auo
}

// SetTitle sets the "title" field.
func (auo *AlbumUpdateOne) SetTitle(s string) *AlbumUpdateOne {
	auo.mutation.SetTitle(s)
	return auo
}

// SetArtist sets the "artist" field.
func (auo *AlbumUpdateOne) SetArtist(s string) *AlbumUpdateOne {
	auo.mutation.SetArtist(s)
	return auo
}

// SetPrice sets the "price" field.
func (auo *AlbumUpdateOne) SetPrice(i int) *AlbumUpdateOne {
	auo.mutation.ResetPrice()
	auo.mutation.SetPrice(i)
	return auo
}

// AddPrice adds i to the "price" field.
func (auo *AlbumUpdateOne) AddPrice(i int) *AlbumUpdateOne {
	auo.mutation.AddPrice(i)
	return auo
}

// Mutation returns the AlbumMutation object of the builder.
func (auo *AlbumUpdateOne) Mutation() *AlbumMutation {
	return auo.mutation
}

// Where appends a list predicates to the AlbumUpdate builder.
func (auo *AlbumUpdateOne) Where(ps ...predicate.Album) *AlbumUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AlbumUpdateOne) Select(field string, fields ...string) *AlbumUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Album entity.
func (auo *AlbumUpdateOne) Save(ctx context.Context) (*Album, error) {
	auo.defaults()
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AlbumUpdateOne) SaveX(ctx context.Context) *Album {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AlbumUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AlbumUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (auo *AlbumUpdateOne) defaults() {
	if _, ok := auo.mutation.UpdateTime(); !ok {
		v := album.UpdateDefaultUpdateTime()
		auo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AlbumUpdateOne) check() error {
	if v, ok := auo.mutation.Price(); ok {
		if err := album.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "Album.price": %w`, err)}
		}
	}
	return nil
}

func (auo *AlbumUpdateOne) sqlSave(ctx context.Context) (_node *Album, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(album.Table, album.Columns, sqlgraph.NewFieldSpec(album.FieldID, field.TypeInt))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Album.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, album.FieldID)
		for _, f := range fields {
			if !album.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != album.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.UpdateTime(); ok {
		_spec.SetField(album.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := auo.mutation.Title(); ok {
		_spec.SetField(album.FieldTitle, field.TypeString, value)
	}
	if value, ok := auo.mutation.Artist(); ok {
		_spec.SetField(album.FieldArtist, field.TypeString, value)
	}
	if value, ok := auo.mutation.Price(); ok {
		_spec.SetField(album.FieldPrice, field.TypeInt, value)
	}
	if value, ok := auo.mutation.AddedPrice(); ok {
		_spec.AddField(album.FieldPrice, field.TypeInt, value)
	}
	_node = &Album{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{album.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
